#!/usr/bin/env bash
# bootstrap.sh — one-time setup after cloning Archive Notes.
#
# The Xcode project is generated by XcodeGen (project.yml is authoritative) and is NOT committed,
# so a fresh clone has no .xcodeproj. This installs XcodeGen if needed and generates the project so
# you can open/build immediately. Safe to re-run (e.g. after adding source files).
# Usage:  ./bootstrap.sh [--open]
set -euo pipefail

# Run from the repo root regardless of where it's invoked (handles the space in the path).
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

say() { printf '\033[1;34m▸\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; }

# 1) Ensure XcodeGen is available (install via Homebrew if possible).
if ! command -v xcodegen >/dev/null 2>&1; then
  say "XcodeGen not found — installing…"
  if command -v brew >/dev/null 2>&1; then
    brew install xcodegen
  else
    err "Homebrew not found. Install it from https://brew.sh then: brew install xcodegen"
    exit 1
  fi
fi
say "Using XcodeGen $(xcodegen --version 2>/dev/null | tail -1)"

# 2) Generate every Xcode project (each directory containing a project.yml).
found=0
while IFS= read -r yml; do
  dir="$(dirname "$yml")"
  found=1
  say "Generating project in ${dir#./} …"
  ( cd "$dir" && xcodegen generate )
done < <(find . -name project.yml -not -path '*/build/*' -not -path '*/.git/*' | sort)

if [ "$found" -eq 0 ]; then err "No project.yml found — are you in the repo root?"; exit 1; fi

say "Done."
echo "  Open the project to build & run (macOS 14+):"
echo "    open macOS/ArchiveNotes.xcodeproj"

# 3) Optional convenience: open the project.
if [ "${1:-}" = "--open" ]; then
  say "Opening the project…"
  open macOS/ArchiveNotes.xcodeproj
fi
